package id.my.alan.minikasir.data.local.db;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.sqlite.db.SupportSQLiteDatabase;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import id.my.alan.minikasir.data.local.dao.ProductDao;
import id.my.alan.minikasir.data.local.dao.SyncQueueDao;
import id.my.alan.minikasir.data.local.dao.TransactionDao;
import id.my.alan.minikasir.data.local.entity.ProductEntity;
import id.my.alan.minikasir.data.local.entity.SyncQueueEntity;
import id.my.alan.minikasir.data.local.entity.TransactionEntity;
import id.my.alan.minikasir.data.local.entity.TransactionItemEntity;

/**
 * The central Room database class for the MiniKasir application.
 *
 * <p>This class acts as the main access point for all local persistence.
 * It follows the <em>singleton pattern</em> (double-checked locking) to ensure
 * that only one database connection is ever open at a time, preventing resource
 * leaks and race conditions.
 *
 * <h3>Entities</h3>
 * <ul>
 *   <li>{@link ProductEntity} — product catalogue</li>
 *   <li>{@link TransactionEntity} — sales transaction headers</li>
 *   <li>{@link TransactionItemEntity} — line items within a transaction</li>
 *   <li>{@link SyncQueueEntity} — offline-first outbox sync queue</li>
 * </ul>
 *
 * <h3>Pre-populated data</h3>
 * On first creation the database is seeded with 5 sample products via the
 * {@link RoomDatabase.Callback#onCreate(SupportSQLiteDatabase)} hook so that
 * the app is immediately usable out of the box.
 *
 * <h3>Schema migrations</h3>
 * Start at version 1. Add {@code Migration} objects and update
 * {@link Database#version()} when the schema changes in future releases.
 */
@Database(
        entities = {
                ProductEntity.class,
                TransactionEntity.class,
                TransactionItemEntity.class,
                SyncQueueEntity.class
        },
        version = 1,
        exportSchema = true
)
public abstract class AppDatabase extends RoomDatabase {

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------

    /** Logical name of the SQLite database file. */
    private static final String DATABASE_NAME = "minikasir.db";

    /**
     * Number of threads in the write executor used by the pre-populate callback.
     * Keep at 1 to serialise all DB writes through a single thread.
     */
    private static final int NUMBER_OF_THREADS = 1;

    // -------------------------------------------------------------------------
    // Singleton instance
    // -------------------------------------------------------------------------

    /** The sole instance of {@link AppDatabase}. Guarded by {@code synchronized}. */
    private static volatile AppDatabase INSTANCE;

    /**
     * Shared executor for running database operations off the main thread.
     * Exposed as package-private so DAOs can use it indirectly via repositories.
     */
    static final ExecutorService databaseWriteExecutor =
            Executors.newFixedThreadPool(NUMBER_OF_THREADS);

    // -------------------------------------------------------------------------
    // Abstract DAO accessors
    // -------------------------------------------------------------------------

    /**
     * Returns the DAO for {@link ProductEntity} operations.
     *
     * @return the {@link ProductDao} implementation generated by Room
     */
    public abstract ProductDao productDao();

    /**
     * Returns the DAO for {@link TransactionEntity} and
     * {@link TransactionItemEntity} operations.
     *
     * @return the {@link TransactionDao} implementation generated by Room
     */
    public abstract TransactionDao transactionDao();

    /**
     * Returns the DAO for {@link SyncQueueEntity} operations.
     *
     * @return the {@link SyncQueueDao} implementation generated by Room
     */
    public abstract SyncQueueDao syncQueueDao();

    // -------------------------------------------------------------------------
    // Singleton factory
    // -------------------------------------------------------------------------

    /**
     * Returns the application-scoped singleton instance of {@link AppDatabase}.
     *
     * <p>Uses double-checked locking to minimise synchronisation overhead after
     * the instance has been initialised.
     *
     * @param context any {@link Context}; the application context is extracted
     *                internally to prevent activity/fragment leaks
     * @return the singleton {@link AppDatabase} instance
     */
    public static AppDatabase getInstance(@NonNull Context context) {
        if (INSTANCE == null) {
            synchronized (AppDatabase.class) {
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(
                                    context.getApplicationContext(),
                                    AppDatabase.class,
                                    DATABASE_NAME)
                            .addCallback(sPrepopulateCallback)
                            .build();
                }
            }
        }
        return INSTANCE;
    }

    // -------------------------------------------------------------------------
    // Pre-populate callback
    // -------------------------------------------------------------------------

    /**
     * Room {@link RoomDatabase.Callback} that seeds 5 sample products into the
     * database on the very first creation. This runs inside a write executor
     * thread so it does not block the main thread.
     */
    private static final RoomDatabase.Callback sPrepopulateCallback = new RoomDatabase.Callback() {

        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);
            // Run the seed on the shared write executor thread.
            databaseWriteExecutor.execute(() -> {
                if (INSTANCE != null) {
                    seedSampleProducts(INSTANCE.productDao());
                }
            });
        }
    };

    /**
     * Inserts 5 representative sample products so that the app has meaningful
     * data to display immediately after installation.
     *
     * @param dao the {@link ProductDao} to use for the inserts
     */
    private static void seedSampleProducts(@NonNull ProductDao dao) {
        long now = System.currentTimeMillis();

        // 1 — Nasi Goreng Spesial
        ProductEntity nasiGoreng = new ProductEntity();
        nasiGoreng.setName("Nasi Goreng Spesial");
        nasiGoreng.setPrice(25_000L);
        nasiGoreng.setStock(50);
        nasiGoreng.setDescription("Nasi goreng dengan telur, ayam, dan sayuran pilihan");
        nasiGoreng.setCreatedAt(now);
        nasiGoreng.setUpdatedAt(now);
        dao.insertProduct(nasiGoreng);

        // 2 — Mie Ayam
        ProductEntity mieAyam = new ProductEntity();
        mieAyam.setName("Mie Ayam");
        mieAyam.setPrice(18_000L);
        mieAyam.setStock(40);
        mieAyam.setDescription("Mie ayam dengan bakso dan pangsit goreng");
        mieAyam.setCreatedAt(now);
        mieAyam.setUpdatedAt(now);
        dao.insertProduct(mieAyam);

        // 3 — Es Teh Manis
        ProductEntity esTeh = new ProductEntity();
        esTeh.setName("Es Teh Manis");
        esTeh.setPrice(5_000L);
        esTeh.setStock(100);
        esTeh.setDescription("Teh manis dingin, segar dan nikmat");
        esTeh.setCreatedAt(now);
        esTeh.setUpdatedAt(now);
        dao.insertProduct(esTeh);

        // 4 — Ayam Goreng
        ProductEntity ayamGoreng = new ProductEntity();
        ayamGoreng.setName("Ayam Goreng");
        ayamGoreng.setPrice(20_000L);
        ayamGoreng.setStock(30);
        ayamGoreng.setDescription("Ayam goreng crispy bumbu rempah khas");
        ayamGoreng.setCreatedAt(now);
        ayamGoreng.setUpdatedAt(now);
        dao.insertProduct(ayamGoreng);

        // 5 — Jus Alpukat
        ProductEntity jusAlpukat = new ProductEntity();
        jusAlpukat.setName("Jus Alpukat");
        jusAlpukat.setPrice(15_000L);
        jusAlpukat.setStock(25);
        jusAlpukat.setDescription("Jus alpukat segar dengan susu dan sirup coklat");
        jusAlpukat.setCreatedAt(now);
        jusAlpukat.setUpdatedAt(now);
        dao.insertProduct(jusAlpukat);
    }
}
